---
- hosts: all
  sudo: yes

  tasks:
    - apt: update_cache=true cache_valid_time=604800
      tags: apt-cache

    - include: vim.yml
      tags: vim
    - include: postgresql.yml
      tags: pgconf
      vars:
        type: web
        total_memory: 395264000
        max_connections: 20

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted
